#!/usr/bin/env python3
"""Render the entities knowledge base into a static HTML site (display phase 2).

Usage:
    python3 scripts/kb-render.py
    python3 scripts/kb-render.py --data entities/data --out entities/site

Pure views on the KB (docs/entities-display.md §4–5): one page per entity, plus
aggregate views — a who's-who index (people), a map (places), and a flora gallery
(plants). These never contain mishna text; appearances are deep links into the
canonical masechot via the anchor scheme in docs/html-format.md.

Reads the YAML source of truth (full fidelity); knowledge.db remains the
cross-entity query index per KB spec §11. Output is derived & gitignored.

Requires: pyyaml.
"""

import argparse
import html
import sys
from pathlib import Path

try:
    import yaml
except ImportError:
    sys.exit("kb-render: PyYAML is required — pip install pyyaml")

ROOT = Path(__file__).resolve().parent.parent
KINDS = {"people": "person", "places": "place", "plants": "plant"}
KIND_LABEL = {"people": "People", "places": "Places", "plants": "Plants"}
KIND_ICON = {"people": "👤", "places": "📍", "plants": "🌿"}

CSS = """
:root { --ink:#1a1a1a; --bg:#fdfdfa; --link:#2a5a8a; --muted:#6b6b66; --rule:#e6e6df; }
* { box-sizing: border-box; }
body { background: var(--bg); color: var(--ink); margin: 0;
  font-family: Georgia, "Times New Roman", serif; line-height: 1.6; }
.he { font-family: "SBL Hebrew","Frank Ruehl CLM","Ezra SIL","David CLM",
  "Noto Serif Hebrew","Times New Roman",serif; direction: rtl; }
main { max-width: 46em; margin: 0 auto; padding: 1.5rem 1.25rem 4rem; }
a { color: var(--link); text-decoration: none; }
a:hover { text-decoration: underline; }
nav.crumbs { font-size: .85rem; color: var(--muted); margin-bottom: 1.5rem; }
h1 { font-size: 2rem; margin: 0 0 .15rem; }
h1 .en { display:block; font-size: 1rem; color: var(--muted); font-weight: normal; }
h2 { font-size: 1.1rem; border-bottom: 1px solid var(--rule); padding-bottom: .25rem;
  margin: 2rem 0 .75rem; }
.tag { display:inline-block; font-size:.72rem; padding:.05rem .45rem; border-radius:1rem;
  background:#eef1f4; color:#3a4a5a; margin-left:.25rem; }
.conf { font-size:.7rem; color:var(--muted); }
.conf.accepted{color:#2e7d32;} .conf.minority,.conf.disputed{color:#b26a00;}
.src { font-size:.7rem; color:var(--muted); }
ul.bare { list-style:none; padding:0; margin:.3rem 0; }
ul.bare li { margin:.25rem 0; }
.meta { color:var(--muted); font-size:.9rem; margin:.25rem 0 1rem; }
.claim { margin:.4rem 0; padding:.4rem .6rem; border-left:3px solid var(--rule); }
.claim.primary { border-left-color: var(--link); }
table { border-collapse: collapse; width:100%; font-size:.95rem; }
th,td { text-align:start; padding:.4rem .5rem; border-bottom:1px solid var(--rule); vertical-align:top; }
th { font-size:.8rem; color:var(--muted); text-transform:uppercase; letter-spacing:.03em; }
.gallery { display:grid; grid-template-columns:repeat(auto-fill,minmax(11rem,1fr)); gap:1rem; }
.card { border:1px solid var(--rule); border-radius:.5rem; padding:.9rem; }
.card .taxon { font-style:italic; color:var(--muted); font-size:.85rem; }
.home { display:grid; grid-template-columns:repeat(3,1fr); gap:1rem; margin-top:2rem; }
.home a { border:1px solid var(--rule); border-radius:.5rem; padding:1.25rem; text-align:center;
  color:var(--ink); font-size:1.1rem; }
.home a .n { display:block; font-size:2rem; color:var(--link); }
footer { color:var(--muted); font-size:.8rem; border-top:1px solid var(--rule);
  margin-top:3rem; padding-top:1rem; }
"""


def esc(x):
    return html.escape(str(x)) if x is not None else ""


def he(text):
    return f'<span class="he">{esc(text)}</span>'


def page(title, body, out_root):
    """out_root: relative prefix from this page's dir to entities/site/."""
    return f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{esc(title)}</title>
<style>{CSS}</style>
</head>
<body>
<main>
<nav class="crumbs"><a href="{out_root}index.html">Mishnah Entities</a></nav>
{body}
<footer>Generated by <code>kb-render.py</code> — a view on the entities knowledge base.
Source of truth: <code>entities/data/</code>.</footer>
</main>
</body>
</html>
"""


def appearances_html(doc, masechot_prefix):
    app = doc.get("appearances") or {}
    mish = app.get("mishnah") or []
    other = app.get("other") or []
    if not mish and not other:
        return "<p class='meta'>No recorded appearances yet.</p>"
    out = []
    if mish:
        links = []
        for ref in mish:
            slug, _, cm = ref.partition(" ")
            ch, _, mi = cm.partition(":")
            href = f"{masechot_prefix}masechot/{slug}.html#mishna-{ch}-{mi}"
            links.append(f'<a href="{href}">{esc(ref)}</a>')
        out.append("<ul class='bare'>" + "".join(f"<li>{l}</li>" for l in links) + "</ul>")
    if other:
        out.append("<p class='meta'>Other: " + ", ".join(esc(o) for o in other) + "</p>")
    return "\n".join(out)


def claim_html(value_html, claim, primary=False):
    conf = claim.get("confidence")
    src = claim.get("source")
    by = claim.get("asserted_by")
    bits = []
    if conf:
        bits.append(f'<span class="conf {esc(conf)}">{esc(conf)}</span>')
    if by:
        bits.append(f'<span class="src">{esc(by)}</span>')
    if src:
        bits.append(f'<span class="src">[{esc(src)}]</span>')
    cls = "claim primary" if primary else "claim"
    return f'<div class="{cls}">{value_html} &nbsp; {" ".join(bits)}</div>'


def entity_link(reg, kind, slug):
    """Link to another entity page if it exists, else show the bare slug."""
    doc = reg.get(kind, {}).get(slug)
    if doc:
        name = (doc.get("names") or {}).get("he") or (doc.get("term") or {}).get("he") or slug
        folder = {"person": "people", "place": "places", "plant": "plants"}[kind]
        return f'<a href="../{folder}/{slug}.html">{he(name)} <span class="src">{esc(slug)}</span></a>'
    return f'<span class="src">{esc(slug)}</span>'


# --------------------------------------------------------------------------- #
# per-entity pages (live at site/<folder>/<slug>.html -> masechot at ../../../)
# --------------------------------------------------------------------------- #
MASECHOT_FROM_ENTITY = "../../../"
SITE_FROM_ENTITY = "../../"


def render_person(doc, reg):
    names = doc.get("names") or {}
    era = doc.get("era") or {}
    rel = doc.get("relationships") or {}
    parts = [f'<h1>{he(names.get("he"))}<span class="en">{esc(names.get("en"))}'
             f'<span class="tag">{esc(doc.get("type"))}</span>'
             f'<span class="tag">{esc(doc.get("status"))}</span></span></h1>']
    meta = []
    if era.get("generation"):
        meta.append(f"Generation {esc(era['generation'])}")
    if era.get("floruit"):
        meta.append(esc(era["floruit"]))
    if meta:
        parts.append(f'<p class="meta">{" · ".join(meta)}</p>')
    if names.get("variants"):
        parts.append("<p class='meta'>Also: " +
                     ", ".join(he(v) for v in names["variants"]) + "</p>")
    for label, key in (("Teachers", "teachers"), ("Students", "students"), ("Family", "family")):
        if rel.get(key):
            parts.append(f"<h2>{label}</h2><ul class='bare'>" +
                         "".join(f"<li>{entity_link(reg, 'person', s)}</li>" for s in rel[key]) +
                         "</ul>")
    if doc.get("bio"):
        parts.append("<h2>Biography</h2>")
        for c in doc["bio"]:
            parts.append(claim_html(esc(c.get("value")), c))
    parts.append("<h2>Appearances</h2>" + appearances_html(doc, MASECHOT_FROM_ENTITY))
    parts.append(ids_html(doc))
    return "\n".join(parts)


def render_place(doc, reg):
    names = doc.get("names") or {}
    geo = doc.get("geo") or {}
    parts = [f'<h1>{he(names.get("he"))}<span class="en">{esc(names.get("en"))}'
             f'<span class="tag">{esc(doc.get("type"))}</span>'
             f'<span class="tag">{esc(doc.get("status"))}</span></span></h1>']
    extra = []
    if names.get("classical"):
        extra.append("Classical: " + ", ".join(esc(c) for c in names["classical"]))
    if geo.get("region"):
        extra.append("Region: " + esc(geo["region"]))
    if geo.get("modern_admin"):
        extra.append(esc(geo["modern_admin"]))
    if geo.get("consensus"):
        extra.append("Identification: " + esc(geo["consensus"]))
    if extra:
        parts.append(f'<p class="meta">{" · ".join(extra)}</p>')
    coords = geo.get("coordinates") or []
    if coords:
        parts.append("<h2>Coordinates</h2>")
        for i, c in enumerate(coords):
            v = c.get("value") or {}
            osm = f'https://www.openstreetmap.org/?mlat={v.get("lat")}&mlon={v.get("lon")}'
            val = f'{esc(v.get("lat"))}, {esc(v.get("lon"))} &nbsp;<a href="{osm}">map ↗</a>'
            parts.append(claim_html(val, c, primary=(i == 0)))
    media = doc.get("media") or {}
    if media.get("photo"):
        parts.append(f'<p class="meta"><a href="{esc(media["photo"])}">Photo ↗</a></p>')
    parts.append("<h2>Appearances</h2>" + appearances_html(doc, MASECHOT_FROM_ENTITY))
    parts.append(ids_html(doc))
    return "\n".join(parts)


def render_plant(doc, reg):
    term = doc.get("term") or {}
    ident = doc.get("identification") or {}
    names = doc.get("names") or {}
    usage = doc.get("usage") or {}
    parts = [f'<h1>{he(term.get("he"))}<span class="en">{esc(term.get("en_common"))}'
             f'<span class="tag">{esc(doc.get("term_type"))}</span>'
             f'<span class="tag">{esc(doc.get("status"))}</span></span></h1>']
    if term.get("variants"):
        parts.append("<p class='meta'>Forms: " +
                     ", ".join(he(v) for v in term["variants"]) + "</p>")
    parts.append("<h2>Identification</h2>")
    if ident.get("display_taxon"):
        parts.append(f'<p class="meta">Displayed as <i>{esc(ident["display_taxon"])}</i> '
                     f'({esc(ident.get("consensus","?"))})</p>')
    for i, c in enumerate(ident.get("candidates") or []):
        v = c.get("value") or {}
        val = f'<i>{esc(v.get("taxon"))}</i> <span class="src">{esc(v.get("rank"))}</span>'
        parts.append(claim_html(val, c, primary=(i == 0)))
    nrows = []
    for label, key in (("Botanical", "botanical"), ("Family", "family")):
        if names.get(key):
            nrows.append(f"{label}: <i>{esc(names[key])}</i>")
    for label, key in (("English", "common_en"), ("Modern Hebrew", "modern_he"), ("Arabic", "arabic")):
        if names.get(key):
            joined = ", ".join(he(x) if key != "common_en" else esc(x) for x in names[key])
            nrows.append(f"{label}: {joined}")
    if nrows:
        parts.append("<h2>Names</h2><ul class='bare'>" +
                     "".join(f"<li>{r}</li>" for r in nrows) + "</ul>")
    if usage.get("halachic"):
        parts.append("<h2>Halachic categories</h2><p>" +
                     " ".join(f'<span class="tag">{esc(t)}</span>' for t in usage["halachic"]) + "</p>")
    media = doc.get("media") or {}
    mlinks = [f'<a href="{esc(media[k])}">{lbl} ↗</a>'
              for k, lbl in (("photo", "Photo"), ("illustration", "Illustration")) if media.get(k)]
    if mlinks:
        parts.append('<p class="meta">' + " · ".join(mlinks) + "</p>")
    parts.append("<h2>Appearances</h2>" + appearances_html(doc, MASECHOT_FROM_ENTITY))
    parts.append(ids_html(doc))
    return "\n".join(parts)


ID_LABELS = {"wikidata_qid": ("Wikidata", "https://www.wikidata.org/wiki/{}"),
             "pleiades_id": ("Pleiades", "https://pleiades.stoa.org/places/{}"),
             "sefaria_slug": ("Sefaria", None)}


def ids_html(doc):
    ids = {k: v for k, v in (doc.get("ids") or {}).items() if v}
    if not ids:
        return ""
    links = []
    for k, v in ids.items():
        label, tpl = ID_LABELS.get(k, (k, None))
        if tpl:
            links.append(f'<a href="{tpl.format(v)}">{esc(label)} ↗</a>')
        else:
            links.append(f"{esc(label)}: {esc(v)}")
    return "<h2>External IDs</h2><p class='meta'>" + " · ".join(links) + "</p>"


RENDERERS = {"person": render_person, "place": render_place, "plant": render_plant}


# --------------------------------------------------------------------------- #
# aggregate pages (live at site/<name>.html -> masechot at ../../, entities at <folder>/)
# --------------------------------------------------------------------------- #
def render_people_index(reg):
    rows = []
    for slug, doc in sorted(reg["person"].items()):
        names = doc.get("names") or {}
        gen = (doc.get("era") or {}).get("generation") or ""
        n = len((doc.get("appearances") or {}).get("mishnah") or [])
        rows.append(f"<tr><td><a href='people/{slug}.html'>{he(names.get('he'))}</a></td>"
                    f"<td>{esc(names.get('en'))}</td><td>{esc(doc.get('type'))}</td>"
                    f"<td>{esc(gen)}</td><td>{n}</td></tr>")
    return ("<h1>Who's Who 👤</h1><table><tr><th>Name</th><th>English</th>"
            "<th>Type</th><th>Gen.</th><th>Mishnayot</th></tr>" + "".join(rows) + "</table>")


def render_places_index(reg):
    rows = []
    for slug, doc in sorted(reg["place"].items()):
        names = doc.get("names") or {}
        geo = doc.get("geo") or {}
        coords = (geo.get("coordinates") or [{}])[0].get("value") or {}
        osm = (f"<a href='https://www.openstreetmap.org/?mlat={coords.get('lat')}"
               f"&mlon={coords.get('lon')}'>{esc(coords.get('lat'))}, {esc(coords.get('lon'))} ↗</a>"
               if coords else "")
        rows.append(f"<tr><td><a href='places/{slug}.html'>{he(names.get('he'))}</a></td>"
                    f"<td>{esc(names.get('en'))}</td><td>{esc(geo.get('region'))}</td>"
                    f"<td>{osm}</td></tr>")
    return ("<h1>Places 📍</h1><p class='meta'>A static index; an interactive map is a later "
            "enhancement (display spec §9).</p><table><tr><th>Name</th><th>English</th>"
            "<th>Region</th><th>Coordinates</th></tr>" + "".join(rows) + "</table>")


def render_plants_index(reg):
    cards = []
    for slug, doc in sorted(reg["plant"].items()):
        term = doc.get("term") or {}
        taxon = (doc.get("identification") or {}).get("display_taxon") or ""
        cards.append(f"<a class='card' href='plants/{slug}.html'>"
                     f"<div>{he(term.get('he'))}</div>"
                     f"<div class='src'>{esc(term.get('en_common'))}</div>"
                     f"<div class='taxon'>{esc(taxon)}</div></a>")
    return "<h1>Flora Gallery 🌿</h1><div class='gallery'>" + "".join(cards) + "</div>"


AGG = {"people": render_people_index, "places": render_places_index, "plants": render_plants_index}


def render_home(reg):
    cells = []
    for folder, kind in KINDS.items():
        cells.append(f"<a href='{folder}.html'><span class='n'>{len(reg[kind])}</span>"
                     f"{KIND_ICON[folder]} {KIND_LABEL[folder]}</a>")
    return ("<h1>Mishnah Entities</h1>"
            "<p class='meta'>People, places, and plants of the Mishnah — a view on the "
            "entities knowledge base.</p><div class='home'>" + "".join(cells) + "</div>")


def load_all(data_dir):
    reg = {"person": {}, "place": {}, "plant": {}}
    for folder, kind in KINDS.items():
        sub = Path(data_dir) / folder
        for path in sorted(sub.glob("*.yaml")):
            with open(path, encoding="utf-8") as f:
                reg[kind][path.stem] = yaml.safe_load(f)
    return reg


def main():
    ap = argparse.ArgumentParser(description="Render the entities KB to a static site.")
    ap.add_argument("--data", default=str(ROOT / "entities" / "data"))
    ap.add_argument("--out", default=str(ROOT / "entities" / "site"))
    args = ap.parse_args()

    reg = load_all(args.data)
    out = Path(args.out)
    written = 0

    def write(rel, body, out_root):
        nonlocal written
        title_map = {"index.html": "Mishnah Entities"}
        title = title_map.get(rel, rel)
        p = out / rel
        p.parent.mkdir(parents=True, exist_ok=True)
        p.write_text(page(title, body, out_root), encoding="utf-8")
        written += 1

    write("index.html", render_home(reg), "")
    for folder, kind in KINDS.items():
        write(f"{folder}.html", AGG[folder](reg), "")
        for slug, doc in sorted(reg[kind].items()):
            write(f"{folder}/{slug}.html", RENDERERS[kind](doc, reg), SITE_FROM_ENTITY)

    print(f"rendered {written} page(s) -> {out}")
    for folder, kind in KINDS.items():
        print(f"  {folder:<8} {len(reg[kind])} entit(ies)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
